// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2i_Bp2d-SmvgnP-KETA2uCsScF7vX4y4',
    appId: '1:1080748012487:web:9fb7324976337709eadfe2',
    messagingSenderId: '1080748012487',
    projectId: 'certifai-2c53f',
    authDomain: 'certifai-2c53f.firebaseapp.com',
    storageBucket: 'certifai-2c53f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARBumUMf0D31gIcqY6x1rJH6sXDv74IT8',
    appId: '1:1080748012487:android:820b0cfe5ee31f50eadfe2',
    messagingSenderId: '1080748012487',
    projectId: 'certifai-2c53f',
    storageBucket: 'certifai-2c53f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCCTOyKDm_bX8G_LkHMD-EEoO-21QMnWZc',
    appId: '1:1080748012487:ios:ced21e7c3019a362eadfe2',
    messagingSenderId: '1080748012487',
    projectId: 'certifai-2c53f',
    storageBucket: 'certifai-2c53f.appspot.com',
    androidClientId: '1080748012487-mbubo8to3idd76srl9s050be9lpq16if.apps.googleusercontent.com',
    iosClientId: '1080748012487-6mrgn47jus07ftajla9hhdqf9ejhovuc.apps.googleusercontent.com',
    iosBundleId: 'com.dmv.frontend',
  );
}
